myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
#     path("", views.index, name="index"),
#     # ex: /polls/5/
#     path("<int:question_id>/details/", views.detail, name="detail"),
#     # ex: /polls/5/results/
#     path("<int:question_id>/results/", views.results, name="results"),
#     # ex: /polls/5/vote/
#     path("<int:question_id>/vote/", views.vote, name="vote"),
# ] 
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), 
    name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp', include('myapp.urls'))
    #path('polls', include('polls.urls'))
]

myapp/models.py
import datetime 

from django.db import models

from django.utils import timezone
# Create your models here.
class Question(models.Model):
  question_text = models.CharField(max_length=250)
  pub_date = models.DateTimeField("date published")
  def __str__(self):
    return self.question_text
  def was_published_recently(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    


class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)
  def __str__(self):
    return self.choice_text

myapp/views.py
from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
#from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

# Create your views here.
'''def index(request):
  #return HttpResponse('<h1>Hello, world.</h1>')
  latest_question_list = Question.objects.order_by("-pub_date")[:5]
  context = {
      "latest_question_list": latest_question_list,
  }
  #template = loader.get_template("polls/index.html")
  
  return render(request, "polls/index.html", context)
  #return HttpResponse(template.render(context,' request))
  #output = ", ".join([q.question_text for q in latest_question_list])
  #return HttpResponse(output) '''
class IndexView(generic.ListView):
  template_name = "polls/index.html"
  context_object_name = "latest_question_list"

  def get_queryset(self):
    return Question.objects.order_by("-pub_date")[:5]

'''Return the last five published questions.'''
  
''' function based viewdef detail(request, question_id):
  #return HttpResponse("You're looking at question %s." % question_id)
   question = get_object_or_404(Question, pk=question_id)
   return render(request, "polls/detail.html", {"question": question})'''

class DetailView(generic.DetailView):
  model = Question
  template_name = "polls/detail.html"

'''def results(request, question_id):
  response = "You're looking at the results of question %s."
  return HttpResponse(response % question_id)'''

class ResultsView(generic.DetailView):
  model = Question
  template_name = "polls/results.html"



def vote(request, question_id):
  #return HttpResponse("You're voting on question %s." % question_id)
  question = get_object_or_404(Question, pk=question_id)
  try:
    selected_choice =question.choice_set.get(pk=request.POST["choice"])
  except (KeyError, Choice.DoesNotExist):
      # Redisplay the question voting form.
      return render(
          request,
          "polls/detail.html",
          {
              "question": question,
              "error_message": "You didn't select a choice.",
          },
      )
  else:
      selected_choice.votes = F("votes") + 1
      selected_choice.save()
      # Always return an HttpResponseRedirect after successfully dealing
      # with POST data. This prevents data from being posted twice if a
      # user hits the Back button.
      return HttpResponseRedirect(reverse("myapp:results", args=(question.id,)))

myapp/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Poll Site</title>
</head>
<body>
  <h1>{{ question.question_text }}</h1>
  <ul>
  {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
  {% endfor %}
  </ul>
  <form action="{% url 'myapp:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
      <legend><h1>{{ question.question_text }}</h1></legend>
      {% if error_message %}<p><strong>{{ error_message }}</strong>  
      </p>{% endif %}
      {% for choice in question.choice_set.all %}
          <input type="radio" name="choice" id="choice{{ 
            forloop.counter }}" value="{{ choice.id }}">
          <label for="choice{{ forloop.counter }}">{{ 
          choice.choice_text }}</label><br>
      {% endfor %}
  </fieldset>
  <input type="submit" value="Vote">
  </form>
</body>
</html>

myapp/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Poll Site</title>
</head>
<body>
  {% if latest_question_list %}
      <ul>
      {% for question in latest_question_list %}
          <!-- <li><a href="/myapp/{{ question.id }}/">  
          {{question.question_text }}</a></li> -->
          <li><a href="{% url 'myapp:detail' question.id %}"> 
          {{question.question_text }}</a></li>
      {% endfor %}
      </ul>
  {% else %}
      <p>No polls are available.</p>
  {% endif %}
</body>
</html>

myapp/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Poll Site</title>
</head>
<body>
  
</body>
</html>